# Generated by Django 3.1.5 on 2021-05-28 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_auto_20210527_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='filters_attributes',
            new_name='filter_attributes',
        ),
    ]
